# Generated by Django 3.2.20 on 2023-08-11 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FeedBack', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubedata',
            name='hashtag',
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to='FeedBack.youtubedata')),
            ],
        ),
    ]
